# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wenjiequ/testjpeg

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wenjiequ/testjpeg

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wenjiequ/testjpeg/CMakeFiles /home/wenjiequ/testjpeg//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wenjiequ/testjpeg/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ippr

# Build rule for target.
ippr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ippr
.PHONY : ippr

# fast build rule for target.
ippr/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ippr.dir/build.make CMakeFiles/ippr.dir/build
.PHONY : ippr/fast

ddraw.o: ddraw.cpp.o
.PHONY : ddraw.o

# target to build an object file
ddraw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ippr.dir/build.make CMakeFiles/ippr.dir/ddraw.cpp.o
.PHONY : ddraw.cpp.o

ddraw.i: ddraw.cpp.i
.PHONY : ddraw.i

# target to preprocess a source file
ddraw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ippr.dir/build.make CMakeFiles/ippr.dir/ddraw.cpp.i
.PHONY : ddraw.cpp.i

ddraw.s: ddraw.cpp.s
.PHONY : ddraw.s

# target to generate assembly for a file
ddraw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ippr.dir/build.make CMakeFiles/ippr.dir/ddraw.cpp.s
.PHONY : ddraw.cpp.s

jpeg.o: jpeg.cpp.o
.PHONY : jpeg.o

# target to build an object file
jpeg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ippr.dir/build.make CMakeFiles/ippr.dir/jpeg.cpp.o
.PHONY : jpeg.cpp.o

jpeg.i: jpeg.cpp.i
.PHONY : jpeg.i

# target to preprocess a source file
jpeg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ippr.dir/build.make CMakeFiles/ippr.dir/jpeg.cpp.i
.PHONY : jpeg.cpp.i

jpeg.s: jpeg.cpp.s
.PHONY : jpeg.s

# target to generate assembly for a file
jpeg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ippr.dir/build.make CMakeFiles/ippr.dir/jpeg.cpp.s
.PHONY : jpeg.cpp.s

jpegwrite.o: jpegwrite.cpp.o
.PHONY : jpegwrite.o

# target to build an object file
jpegwrite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ippr.dir/build.make CMakeFiles/ippr.dir/jpegwrite.cpp.o
.PHONY : jpegwrite.cpp.o

jpegwrite.i: jpegwrite.cpp.i
.PHONY : jpegwrite.i

# target to preprocess a source file
jpegwrite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ippr.dir/build.make CMakeFiles/ippr.dir/jpegwrite.cpp.i
.PHONY : jpegwrite.cpp.i

jpegwrite.s: jpegwrite.cpp.s
.PHONY : jpegwrite.s

# target to generate assembly for a file
jpegwrite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ippr.dir/build.make CMakeFiles/ippr.dir/jpegwrite.cpp.s
.PHONY : jpegwrite.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ippr.dir/build.make CMakeFiles/ippr.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ippr.dir/build.make CMakeFiles/ippr.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ippr.dir/build.make CMakeFiles/ippr.dir/main.cpp.s
.PHONY : main.cpp.s

morpho.o: morpho.cpp.o
.PHONY : morpho.o

# target to build an object file
morpho.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ippr.dir/build.make CMakeFiles/ippr.dir/morpho.cpp.o
.PHONY : morpho.cpp.o

morpho.i: morpho.cpp.i
.PHONY : morpho.i

# target to preprocess a source file
morpho.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ippr.dir/build.make CMakeFiles/ippr.dir/morpho.cpp.i
.PHONY : morpho.cpp.i

morpho.s: morpho.cpp.s
.PHONY : morpho.s

# target to generate assembly for a file
morpho.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ippr.dir/build.make CMakeFiles/ippr.dir/morpho.cpp.s
.PHONY : morpho.cpp.s

util.o: util.cpp.o
.PHONY : util.o

# target to build an object file
util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ippr.dir/build.make CMakeFiles/ippr.dir/util.cpp.o
.PHONY : util.cpp.o

util.i: util.cpp.i
.PHONY : util.i

# target to preprocess a source file
util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ippr.dir/build.make CMakeFiles/ippr.dir/util.cpp.i
.PHONY : util.cpp.i

util.s: util.cpp.s
.PHONY : util.s

# target to generate assembly for a file
util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ippr.dir/build.make CMakeFiles/ippr.dir/util.cpp.s
.PHONY : util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ippr"
	@echo "... ddraw.o"
	@echo "... ddraw.i"
	@echo "... ddraw.s"
	@echo "... jpeg.o"
	@echo "... jpeg.i"
	@echo "... jpeg.s"
	@echo "... jpegwrite.o"
	@echo "... jpegwrite.i"
	@echo "... jpegwrite.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... morpho.o"
	@echo "... morpho.i"
	@echo "... morpho.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

